<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Products ตาม format pr_code จาก DBF: OEM-CHOVNAA1017180, OEM-CHOBTAA107003140
        DB::table('products')->insert([
            [
                'product_id'    => 'OEM-CHOVNAA1017180',
                'name'          => 'ชิ้นส่วน CHO VN AA 1017180',
                'category_id'   => 'CHO',
                'stock_min'     => 10,
                'stock_max'     => 500,
                'current_stock' => 0,
                'size'          => '10x17x180',
                'pack'          => 'ชิ้น',
                'weight_per_kg' => 0.50,
                'weight_total'  => 0,
                'warehouse_id'  => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'product_id'    => 'OEM-CHOVNAA10181100',
                'name'          => 'ชิ้นส่วน CHO VN AA 10181100',
                'category_id'   => 'CHO',
                'stock_min'     => 10,
                'stock_max'     => 500,
                'current_stock' => 0,
                'size'          => '10x18x1100',
                'pack'          => 'ชิ้น',
                'weight_per_kg' => 0.75,
                'weight_total'  => 0,
                'warehouse_id'  => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'product_id'    => 'OEM-CHOBTAA107003140',
                'name'          => 'ชิ้นส่วน CHO BT AA 107003140',
                'category_id'   => 'BT',
                'stock_min'     => 5,
                'stock_max'     => 300,
                'current_stock' => 0,
                'size'          => '70x31x40',
                'pack'          => 'ชิ้น',
                'weight_per_kg' => 0.30,
                'weight_total'  => 0,
                'warehouse_id'  => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'product_id'    => 'OEM-CHOBTAA107002125',
                'name'          => 'ชิ้นส่วน CHO BT AA 107002125',
                'category_id'   => 'BT',
                'stock_min'     => 5,
                'stock_max'     => 300,
                'current_stock' => 0,
                'size'          => '70x21x25',
                'pack'          => 'ชิ้น',
                'weight_per_kg' => 0.25,
                'weight_total'  => 0,
                'warehouse_id'  => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'product_id'    => 'OEM-CHOVNBB2025100',
                'name'          => 'ชิ้นส่วน CHO VN BB 2025100',
                'category_id'   => 'VN',
                'stock_min'     => 10,
                'stock_max'     => 400,
                'current_stock' => 0,
                'size'          => '20x25x100',
                'pack'          => 'ชิ้น',
                'weight_per_kg' => 0.40,
                'weight_total'  => 0,
                'warehouse_id'  => 2,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'product_id'    => 'OEM-CHOVNBB2030150',
                'name'          => 'ชิ้นส่วน CHO VN BB 2030150',
                'category_id'   => 'VN',
                'stock_min'     => 10,
                'stock_max'     => 400,
                'current_stock' => 0,
                'size'          => '20x30x150',
                'pack'          => 'ชิ้น',
                'weight_per_kg' => 0.55,
                'weight_total'  => 0,
                'warehouse_id'  => 2,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'product_id'    => 'OEM-CHOBTCC305080',
                'name'          => 'ชิ้นส่วน CHO BT CC 305080',
                'category_id'   => 'BT',
                'stock_min'     => 5,
                'stock_max'     => 200,
                'current_stock' => 0,
                'size'          => '30x50x80',
                'pack'          => 'ชิ้น',
                'weight_per_kg' => 0.60,
                'weight_total'  => 0,
                'warehouse_id'  => 2,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'product_id'    => 'OEM-GENERAL001',
                'name'          => 'สินค้า OEM ทั่วไป 001',
                'category_id'   => 'OEM',
                'stock_min'     => 20,
                'stock_max'     => 1000,
                'current_stock' => 0,
                'size'          => null,
                'pack'          => 'ชิ้น',
                'weight_per_kg' => 0.20,
                'weight_total'  => 0,
                'warehouse_id'  => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
        ]);
    }
}
